
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'thesis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'thesis'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  thesis:
      # Applies to all files under models/example/
      dblp_api:
        schema: dblp_api
      # arxiv_clean:
      #   schema: arxiv_clean
      core:
        schema: core
      integration:
        schema: integration
      lncs_front_matter:
        schema: lncs_front_matter
      springer_lncs:
        schema: springer_lncs
      dblp_dump:
        schema: dblp_dump
      acm_analysis:
        schema: acm_analysis
      elsevier_analysis:
        schema: elsevier_analysis
          
seeds:
  thesis:
    schema: seed
    core:
      schema: core
    dblp_api:
      schema: dblp_api
    springer_lncs:
      schema: springer_lncs
    acm:
      schema: acm
    

# on-run-end: "drop schema tempory_tables cascade"
      
